markdown: redcarpet
pygments: true

title_tag_text: Blindstore - Private Information Retrieval Datastore
h1_tag_text: Blindstore

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
